### ISSUE TITLE
[SDL 0274] Add preferred FPS to VideoStreamingCapability

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_javascript_suite#115]
Proposal: [Add preferred FPS to VideoStreamingCapability](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0274-add-preferred-FPS.md)

> This proposal extends SDL video streaming feature by adding preferred FPS to `VideoStreamingCapability`, so that frame rate of video streaming can be adjusted per OEM.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/913

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions.  The revisions will include the items listed in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/913#issuecomment-579062117) from the author.

> The proposal .md file was updated to reflect these revisions on 2/10/2020.

**Comment by shiniwat** [comment]
Sorry, I overlooked this issue. This issue is actually covered by PR for SDL 0292 at https://github.com/smartdevicelink/sdl_java_suite/pull/1389. The PR for SDL 0292 actually includes prefferred FPS feature.

**Comment by theresalech** [comment]
@shiniwat, thanks for letting us know! I believe this comment was meant for the SDL 0274 implementation issue in the _Java Suite_ library: https://github.com/smartdevicelink/sdl_java_suite/issues/1268. If that is correct, can you please leave this comment on that issue for visibility? Thank you!

**Comment by shiniwat** [comment]
Hi @theresalech,
I'm sorry, I was confused -- I meant sdl_java_suite (https://github.com/smartdevicelink/sdl_java_suite/issues/1268); obvisouly not the sdl_javascript_suite. Please disregard my previous comment. Thanks.

**Comment by shiniwat** [comment]
I have looked into current sdl_javascipt_suite code, and confirmed that all Proxy layer's codes are generated by Proxy Library RPC generator.
Therefore, once my rpc_spec PR at https://github.com/smartdevicelink/rpc_spec/pull/229 is merged, and rpc_spec submodule is updated, preferredFPS parameter will be added to VideoStreamingCapability.js automatically, and then this issue can be resolved.

**Comment by crokita** [comment]
@shiniwat Hello. This project still tracks the changes made to the generated RPC files, so even though our npm build script will generate all those files from the rpc_spec once it updates, a PR would still need to be made here to include those new generated file changes in the project before being resolved.

**Comment by shiniwat** [comment]
Hi @crokita, 
Understood. Thanks for clarification. I will make the change after rpc_spec has been updated.

**Comment by jordynmackool** [comment]
Hi @shiniwat, this PR should point to the branch of the RPC Spec that contains the changes needed for this feature.

RPC Spec changes are not merged until the feature has been properly tested with all the required projects and it is confirmed the feature will make it into the slated releases.

Once this PR is updated and tested against the RPC Spec feature branch, please tag me requesting a review.
