### ISSUE TITLE
[SDL 0272] JavaScript Suite SDL Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_javascript_suite#123]
Proposal: [JavaScript Suite SDL Manager](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0272-sdl-javascript-manager-layer.md)

> In a similar vein to [this proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0171-android-manager-apis.md), the goal is to introduce a manager layer to the JavaScript Suite, closely matching the Java Suite and iOS manager APIs. These manager classes are designed to abstract out complex flows and states for common tasks, such as file handling and displaying information to the screen. 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/901

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the revisions listed below:

- (Item 2) Pass an AppConfig instance into the SDLManager constructor.  The SDLManager `start()` method can perform the basic validation checks prior to starting the LifecycleManager to ensure the minimum properties of an AppConfig are provided, as well as a ManagerListener being defined.
- (Item 3) Single-method listeners to be replaced with simple JavaScript-oriented callback functions.
- (Item 7) Promises should be returned by manager methods which ultimately send one or more RPCs resulting in a single response. Developers then have the freedom to decide if/how they would like to handle the resolution or rejection of the RPC response. 
- (Item 12) Remove `getInternalInterface()` in favor of utilizing the reference to the LifecycleManager

> The proposal .md file was updated to reflect these revisions on 3/3/2020.

**Comment by crokita** [comment]
MenuManager needs to be implemented still
