### ISSUE TITLE
Connection doesn't get disposed of properly when the app is finished

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#142]
### Bug Report
For client applications specifically, such as TCP client apps or WS client apps, when the sdlManager's dispose method is invoked, the underlying transport connection does not shut down. 

When dispose is called, the TCP node app should have no more running process, and for the WS app in the browser, you should be able to see in the network tab for that connection that it has closed.

**Comment by theresalech** [comment]
Closed via #146
