### ISSUE TITLE
Remove RPC_SPEC numeric enum generation / define custom numeric enums

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_javascript_suite#143]
### Bug Report
There was a big internal discussion about so-called "numeric" enums, which are enum values in the RPC spec that have a `value` attribute with a numeric value. The conclusion was that Core is capable of receiving Strings or Integers but will only send the string. This means that, depending on the context, we may need to support the string value or the integer value. 

There are basically three enums that support `value` with an integer: `LightName`, `messageType`[sic], and `PredefinedWindow`. `messageType` is only used in the protocol binary header as an integer, not a string. `PredefinedWindow`'s value is only used in other RPC_SPEC parameters that ask for an integer value. Its string value is never used. `LightName` appears to only ever be used as a string value.

For this reason, the iOS and Java_Suite generators will now only create the String enums. To align with the iOS and Java Suite generators, the generated code will then have to be altered as necessary to support integers. This could be either by _replacing_ the string enums that need integer enums with integer equivalents, _or_ by adding integer equivalents into the string enum class.

**Comment by theresalech** [comment]
Closed via #185
