### ISSUE TITLE
Coding Style Guideline Updates

### ISSUE THREAD

**Issue by russjohnson09** [smartdevicelink/sdl_javascript_suite#15]
"Acronyms should either be all uppercased or lowercased." This rule isn't currently being followed for class names like JsonRpcMarshaller SdlPsm. The class names are easy to read this way and so the rule should be removed from the guidelines. Proper camelcase, pascal case, and uppercase with underscores for constants should still be used.

**Comment by crokita** [comment]
I'd like to make a small addition, too.

Documented methods have the following form:

```
/**
    * [Description of what the method does.]
    * @param [param_name] [param_description]
    * @return [What the method returns.]
*/
```

Just to make it clearer, there should be some sort of separator between [param_name] and [param_description], like a hyphen. The official jsdoc dev site has an example: https://devdocs.io/jsdoc/howto-commonjs-modules

Also see #11 for an existing example in the project.
