### ISSUE TITLE
Wrong build file reference in example apps

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#177]
### Bug Report
In the Node TCP example app for the release candidate, it is referencing the node build file outside of its respective folder, in `lib/node/dist/SDL.min.js`. It should be referencing the build file in the same directory instead. Additionally, the `ws` module should be a package dependency. Also check the other example apps for similar issues

**Comment by bilal-alsharifi** [comment]
this issue exists in both `node/hello-sdl-tcp` & `node/hello-sdl` apps out of the 4 apps in the release brach.

**Comment by theresalech** [comment]
Fixed via https://github.com/smartdevicelink/sdl_javascript_suite/pull/208
