### ISSUE TITLE
Unexpected RPC Response may cause sendRpc method to hang

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#231]
### Bug Report
There can be a case where a head unit doesn't understand newer RPCs and thus will return a GenericResponse as a response to a request. Due to how the send rpc message method works (this needs to be verified), there may be issues with the sendRpc never resolving because it is waiting for the response of a matching function id. The suggestion is to listen for GenericResponse on every request (still check the correlation id), and resolve/reject the value.

If any other unexpected condition were to happen, the promise may still not resolve. One way to have eventual resolution is to have a timeout for every request, which will reject the promise after a certain amount of time has passed.

**Comment by theresalech** [comment]
Closed via #232
