### ISSUE TITLE
[SDL 0200] - Removing URL Parameter Max Length

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_javascript_suite#252]
Proposal: [Removing URL Parameter Max Length](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0200-Removing-URL-Param-Max-Length.md)

> This proposal is to remove maximum length attribute for URL strings provided to OnSystemRequest, StartStream and StartAudioStream and let the URL strings be of any length permissible by the system architecture.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/603

Steering Committee Decision:

> The Steering Committee accepted this proposal on 10/16/2018. The following was discussed in the Steering Committee meeting on 2018-10-16, with regards to this proposal: Although there are no iOS or Android limitations over the size and length of URLs, excessively long ones may take a long time to create / parse, and extensive data should be sent via a method that is not a URL (e.g. JSON in the bulk data).
Lastly, while it's understood that SDLC members cannot share all use cases for features publicly, it was acknowledged that in the future, when requesting specific features, it is helpful to have real world examples to better understand the reasoning and planned implementation for the requested changes.

**Comment by vladmu** [comment]
@theresalech, @crokita could you assist what changes are expected here? We've checked the existing lib/js/src/rpc/messages/OnSystemRequest.js and didn't find any mentions of `maxlength` attribute in the code. Also, we didn't find any existing tests for this attribute. It seems the change https://github.com/smartdevicelink/rpc_spec/pull/225/files doesn't affect the library and this issue could be closed without any changes.

**Comment by theresalech** [comment]
@vladmu, it's been determined that sdl_javascript_suite code changes are not required.  However, we should still add unit tests for this feature.  Can you please provide?  Thank you!

**Comment by vladmu** [comment]
@theresalech, @crokita fix me if I'm wrong, but the library doesn't check this `maxlength` limitation on the own side. What unit tests are you expecting here? Could you provide the reference to similar existing tests in the library?

**Comment by crokita** [comment]
@vladmu Hello. The unit tests would check that the library can handle the new change made to this attribute, so that a value can be set that goes beyond the max length bound. We don't have existing tests that cover a case like this in the library.

**Comment by vladmu** [comment]
@crokita I understand, and in case if the library previously had the restriction, it would make sense, but when no restrictions found before in the code and no changes required by this proposal, what could we check in the unit test? And the second point, `OnSystemRequest` is the notification message, not the request, therefore the library will only read the `url` parameter from the `Core` when this notification occurs and process it as is without any restrictions. So I still don't see the case for the unit test as we don't change anything in the code. If you have the reference for similar cases in other libraries, eg. Java, it would be also helpful.

**Comment by joeygrover** [comment]
@vladmu Even if the library has not had explicit restrictions on the URL length in the past, the supplied URL lengths would have still been in range of the RPC spec definition ie, any URL supplied in the `OnSystemRequest` would have been limited. Therefore, we can only say for certain that the library will handle up to the previous limit which would make the limit implicit. There is no test to test beyond that limit yet and that is what we are asking for. We have to actually be sure that the library itself can handle, as you say, an unlimited length url or at least know its bounds. Otherwise we are simply assuming that is the case with no tests to confirm it is true.

**Comment by vladmu** [comment]
@joeygrover @crokita thank you for your patience and answers, I've created the PR, please check if I understood you correctly.

**Comment by vladmu** [comment]
Hi @joeygrover @crokita, we are waiting for your feedback regarding the unit test we've done in PR #271 to make the same in Android and iOS libraries. Thank you!
