### ISSUE TITLE
sendRpcsResolve and sendSequentialRpcsResolve required second argument

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#272]
### Bug Report
The SdlManager `sendRpcsResolve` and `sendSequentialRpcsResolve`'s `onUpdate` argument is required when it should be optional.

##### Expected Behavior
Only one argument should be required for the methods

##### Observed Behavior
An error happens when not including the second argument

**Comment by theresalech** [comment]
Closed via #274
