### ISSUE TITLE
Setting LifecycleConfigurationUpdate's TTS Names is required

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#273]
### Bug Report
`_checkLifecycleConfiguration` errors when trying to set ChangeRegistration's TTSName to null, which can happen when lifecycleConfigUpdate doesn't set a TTSName

##### Expected Behavior
TTS Names should be optional to set

##### Observed Behavior
TTS Names is required to set

**Comment by theresalech** [comment]
Closed via #275
