### ISSUE TITLE
Ordering of HMI listener invocation

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#279]
### Bug Report
The order in which RPC listeners are set up depends on whether your app is a cloud app. Non-cloud apps start up in a different order than cloud apps, and so when the HMI level changes, either the app will be notified of the change first, or the managers in the library will. This leads to some unexpected behavior where manager logic may not be able to run before the app does, and so managers like the PermissionManager are not updated in time for the app to check permission statuses on start up.

**Comment by theresalech** [comment]
Closed via #281
