### ISSUE TITLE
"Return to WEB_VIEW" button is not displayed in the Options on HMI

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_javascript_suite#321]
**Bug Report**
"Return to WEB_VIEW" button is not displayed in the Options on HMI
WebEngine App does not send AddCommand RPC ( Rpc: "AddCommand" Type: "request" Params: {"cmdID":1001,"menuParams":{"menuName":"Return to WEB_VIEW","position":0,"parentID":0}})) to SDL

**Preconditions:**

1. HMI and SDL are started
2. Web app is registered and activated successfully
HMI displays the WEB_VIEW template

**Reproduction Steps**

Press "Show menu" button on HMI
1. Web app sends ShowAppMenu: {}

**Expected Behavior**

Adding return to WEB_VIEW template command
1. Web app sends AddCommand request
AddCommand: {"cmdID":1001,"menuParams":{"menuName":"Return to WEB_VIEW","position":0,"parentID":0}}
2. SDL → HMI: UI.AddCommand: { "appID":753901101,"cmdID":1001,"menuParams":
{"menuName":"Return to WEB_VIEW","parentID":0,"position":0}}}
3. HMI -> SDL: UI.AddCommand:{ code":0 }
4. SDL → Web app: AddCommand:{"resultCode": "SUCCESS ", "success":true}
5. "Return to WEB_VIEW" button is displayed in Options on HMI*

**Observed Behavior**
"Return to WEB_VIEW" button is not displayed  in Options on HMI
Web app does not send AddCommand(Return to WEB_VIEW) request

OS & Version Information

OS/Version: Ubuntu 18.04
Sdl_javascript_suite: https://github.com/smartdevicelink/sdl_javascript_suite(3220edd)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop(6d32f1b)

Logs:
[SDL_HMI_logs.zip](https://github.com/smartdevicelink/sdl_javascript_suite/files/5260867/SDL_HMI_logs.zip)

**Comment by VjKlepikov** [comment]
Please notice this is regression issue

**Comment by AKalinich-Luxoft** [comment]
@theresalech please notice PR with fix is ready for Livio review

**Comment by theresalech** [comment]
@AKalinich-Luxoft can you please pull the latest `develop` and let us know if this issue is still reproducible?

**Comment by AKalinich-Luxoft** [comment]
@theresalech yes, it is still actual for latest develop. Fix #319 is still actual
