### ISSUE TITLE
PermissionManager with early return in _notifyListeners

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#403]
### Bug Report
The return is misplaced inside the for loop, meaning only one element at most is handled for the permission filters. The return statement should be at the end of the method.

##### Reproduction Steps
0. Set the policy table to only permit AddCommand on FULL
1. Setup permission listeners for AddCommand/AddSubMenu before startup, with permission group type ANY
2. Start the app
3. Set the HMI level to FULL and then LIMITED/BACKGROUND

##### Expected Behavior
The listeners should fire whenever the app is brought to FULL or BACKGROUND

##### Observed Behavior
The listeners do not fire when set to BACKGROUND

##### Browser & Version Information
All versions and environments affected

##### Test Case, Sample Code, and / or Example App
```
this._permissionManager.addListener(
                    [
                        new SDL.manager.permission.PermissionElement(
                            SDL.rpc.enums.FunctionID.AddCommand
                        ),
                        new SDL.manager.permission.PermissionElement(
                            SDL.rpc.enums.FunctionID.AddSubMenu
                        ),
                    ],
                    SDL.manager.permission.enums.PermissionGroupType.ANY,
                    (allowedPermissions, permissionGroupStatus) => {
                        console.log('permissions changed!');
                        console.log('Allowed Permissions: ', allowedPermissions);
                        console.log('Permission Group Status: ', permissionGroupStatus);
                        this._logPermissions();
                    }
                );
```

**Comment by jordynmackool** [comment]
Closed via https://github.com/smartdevicelink/sdl_javascript_suite/pull/404
