### ISSUE TITLE
Audio files do not play through the Alert Manager

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#406]
### Bug Report
Using the AlertManager to send an AlertView with an audio file in the payload will not be played when shown on the HMI.

##### Reproduction Steps
1. Make an AlertView
2. Add a sound SdlFile to the AlertView as an MP3 file type
3. Send it

##### Expected Behavior
The sound should play

##### Observed Behavior
The sound does not play

##### Browser & Version Information
All versions and environments are affected

##### Test Case, Sample Code, and / or Example App
```
const audioFileOnlyAlert = new SDL.manager.screen.utils.AlertView()
        .setAudio(new SDL.manager.screen.utils.AlertAudioData(null, null,
            new SDL.manager.file.filetypes.SdlFile()
                .setName('sound-file')
                .setFilePath(<file location>)
                .setType(SDL.rpc.enums.FileType.AUDIO_MP3)
        ));
```

**Comment by jordynmackool** [comment]
closed via https://github.com/smartdevicelink/sdl_javascript_suite/pull/408
