### ISSUE TITLE
Library should report 1.3.0 as its version now

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#410]
### Bug Report
Log 1.3.0 for the upcoming release

##### Expected Behavior
The library logs version 1.3.0

##### Observed Behavior
The library logs version 1.2.0

##### Browser & Version Information
Current version and all environments are affected

**Comment by jordynmackool** [comment]
Closed via: https://github.com/smartdevicelink/sdl_javascript_suite/pull/409
