### ISSUE TITLE
ChoiceSetManager errors when presenting choices followed by keyboard

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#411]
### Bug Report
When attempting to use the ChoiceSetManager to first send a choice set, and then immediately after presenting a keyboard, if the user selects a choice option the library will error out due to _pendingPresentationSet not being a valid value anymore.

##### Reproduction Steps
1. Call screenManager.presentChoiceSet() without setting a listener for the choice set
2. Call screenManager.presentKeyboard()
3. Dismiss the keyboard if it shows up and select a choice item before it's dismissed

##### Expected Behavior
The choice should be selected without issues

##### Observed Behavior
The library errors about lack of a ChoiceSetSelectionListener

##### Browser & Version Information
All environments affected

##### Code Example
```
    const choiceCell1 = new SDL.manager.screen.choiceset.ChoiceCell('hello 1')
        .setSecondaryText('hi 1')
        .setTertiaryText('how are you 1')
        .setVoiceCommands(['choice cell 1'])

    const choiceCell2 = new SDL.manager.screen.choiceset.ChoiceCell('hello 2')
        .setSecondaryText('hi 2')
        .setTertiaryText('how are you 2')
        .setVoiceCommands(['choice cell 2'])

    await screenManager.preloadChoices([choiceCell1, choiceCell2]);
    const choiceSet = new SDL.manager.screen.choiceset.ChoiceSet('hello 9', [choiceCell1, choiceCell2]);
    screenManager.presentChoiceSet(choiceSet, SDL.rpc.enums.InteractionMode.MANUAL_ONLY);

    screenManager.presentKeyboard('hello');
```

**Comment by jordynmackool** [comment]
Closed by https://github.com/smartdevicelink/sdl_javascript_suite/pull/412
