### ISSUE TITLE
Create Node.js Sample App

### ISSUE THREAD

**Issue by nickschwab** [smartdevicelink/sdl_javascript_suite#43]
#### Expected Behavior
Create an example Node.js app using the SDL JavaScript library classes.

The example app should register, display an app icon, and perform a `show` command.

**Comment by crokita** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Future manticore issue to look at: setinteriorvehicle data sometimes REJECTS](https://trello.com/c/9pQjdUit/1361-future-manticore-issue-to-look-at-setinteriorvehicle-data-sometimes-rejects)
