### ISSUE TITLE
Choice Set Manager uniqueness doesn't take into account loaded cells

### ISSUE THREAD

**Issue by renonick87** [smartdevicelink/sdl_javascript_suite#478]
### Bug Report
In the choice set manager, cells that are already loaded on the module need to be taken into account for uniqueness. Currently, it does not, which can lead to clashes when trying to present new cells.

##### Reproduction Steps
1. Using a sub-7.1.0 module
1. Load a cell on the head unit
1. Attempt to load a unique cell with identical primary text

##### Expected Behavior
The new cell has a unique identifier appended to it.

##### Observed Behavior
The cell fails to load.

**Comment by jordynmackool** [comment]
Closed by https://github.com/smartdevicelink/sdl_javascript_suite/pull/477.
