### ISSUE TITLE
Add Audio Streaming to Protocol Layer 

### ISSUE THREAD

**Issue by russjohnson09** [smartdevicelink/sdl_javascript_suite#50]
Add the ability to request an audio service (referred to as a PCM service type but the javascript sdk refers to it as simply an audio service type), send raw packets using this audio service, and end the individual audio service without closing the entire session.

**Comment by russjohnson09** [comment]
[The protocol spec](https://smartdevicelink.com/en/guides/sdl-overview-guides/protocol-spec/) has information what information is required for the start service. No params are required for the request and for the response mtu is returned. The mtu is already saved in SdlProtocolBase by service type.

SdlSession has a method for ending an individual service but it needs to be added to SdlProtocolBase. SdlSession and SdlProtocolBase both need a method for sending packets. Right now only rpcs are allowed to be sent. The AudioServiceManager and StreamPacketizer will take care of sending the audio packets, but SdlProtocolBase should still be able to send raw packets.

**Comment by russjohnson09** [comment]
Here is how audio streaming is done using the java audio service manager.
https://www.smartdevicelink.com/en/guides/android/video-streaming-for-navigation-apps/audio-streaming/

**Comment by russjohnson09** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Add Audio Streaming to Protocol Layer [.5]](https://trello.com/c/YJbgxy7j/1350-2-add-audio-streaming-to-protocol-layer-5)

**Comment by crokita** [comment]
Changed merged into develop
