### ISSUE TITLE
Attempting to Send Voice Command with No Strings Fails to Log Error

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#529]
### Bug Summary

When trying to send a VoiceCommand containing no or invalid command strings using VoiceCommandManager, it fails to send as expected, but no error is logged to explain this behavior to the app developer.

### Reproduction Steps

1. Create a voice command array with some voice commands that have empty or blank strings.
2. Make one of the voice commands contain only invalid strings
3. Send the voice command array using `setVoiceCommands`

Expected Behavior:
The library should log that an invalid voice command string was used in a voice command. The library should log that a voice command will not be uploaded due to no valid voice command strings.

Observed Behavior:
Nothing is logged.

### Which projects have you seen this bug on?

Vanilla JavaScript, Node.js

### JavaScript Version(s)

1.5.0

### Testing Environment(s)

```markdown
SDL Core v8.0.0 + Generic_HMI v0.11.0
```

**Comment by theresalech** [comment]
Closed via #530
