### ISSUE TITLE
WebApp does not send Alert request by press 'Alert command' button on HMI

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_javascript_suite#533]
### Bug Summary

WebApp does not send Alert request by press 'Alert command' button on HMI

### Reproduction Steps

1. Core is built with DWEBSOCKET_SERVER_TRANSPORT_SUPPORT set to `true
2. SmartDeviceLink.ini file is modified: ;WSServerCertificatePath = server-cert.pem ;WSServerKeyPath = server-key.pem ;WSServerCACertificatePath = ca-cert.pemare commented out
3. Update preloaded_pt.json: Add to "app_policies"
 {"hello-webengine4": {
   "AppHMIType": [ "WEB_VIEW" ],
    "keep_context": false,
    "steal_focus": false,
    "priority": "NONE",
    "default_hmi": "NONE",
    "groups": ["Base-4", "WidgetSupport"],
     "hybrid_app_preference": "CLOUD",
     "enabled": false,
     "transport_type ": "WS"}

4. SDL and HMI are started
5. In HMI folder, run `./deploy_server.sh` as a back-end process
6. On HMI → Apps →Apps Store → Set Apps Properties → Available applications → Hello WebEngine3 – Set
( Alternative steps manually: On HMI, go to apps->App Store→Set App Properties )
Add properties for hello-webengine4 app:

{
  "nicknames": [
    "Hello WebEngine4"
  ],
  "policyAppID": "hello-webengine4",
  "enabled": true,
  "transportType": "ws",
  "hybridAppPreference": "BOTH"
}

7. Click Set and make sure that app showed in the apps list ( On HMI → Apps →Apps Store → Set Apps Properties → Set )

HMI → SDL: SetAppProperties ( properties: { nicknames: { "Hello WebEngine4" } , policyAppID:"hello-webengine4", enabled: true, transportType:"ws", hybridAppPreference: "BOTH" }
SDL → HMI : SetAppProperties ( { success:true, resultCode: "SUCCESS" } ))
SDL → HMI: UpdateAppList: (... {"applications":["appName":"Hello WebEngine4"... ] ... )
HMI → SDL : UpdateAppList response { SUCCESS }

The Web app is visible in the main window on the HMI

8. Build SDL.min.js for WebEngine App HMI type WEB_VIEW
Copy the content of folder sdl_javascript_suite/examples/webengine/hello-sdl from https://github.com/smartdevicelink/sdl_javascript_suite to the folder sdl_hmi/web_engine/hello-webengine4
Update manifest.js file with content hello-webengine3 -> hello-webengine4

9. Activate a Web app (WEB_VIEW) on the HMI

10. Change Template to "WEB_VIEW"
Go to -> Options -> Return to WEB_VIEW
App sends "Show" request for the main window with "templateConfiguration" ( "template":"WEB_VIEW" )

11. On HMI press 'Alert command' button

**Expected Behavior:**
The alert POP-UP is displayed on HMI.
WebApp -> SDL: Alert: {... alertText1:Test Alert ...}
SDL -> HMI: UI.Alert:  {"alertStrings":[ {"fieldName":"alertText1","fieldText":"Test Alert"}]... param]}}
HMI -> SDL: UI.OnSystemContext: {"systemContext":"ALERT","appID":..}}

**Observed Behavior:**
WebApp does not send Alert request by press 'Alert command' button on HMI

No Images to upload for alert
_PresentAlertOperation.js:144 No audio files need to be uploaded for alert
_PresentAlertOperation.js:249 There was an error presenting the alert: Mandatory parameters are missing
_PresentAlertOperation.js:509 Finishing present alert operation

### Testing Environment(s)

```markdown
OS/Version: Ubuntu 18.04
SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/release/8.1.0 (6b423eb )
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.7.0 (31eed2d)
WebApp: https://github.com/smartdevicelink/sdl_javascript_suite/tree/develop (f541e2f)
```

### Relevant log output
[Logs2.zip](https://github.com/smartdevicelink/sdl_javascript_suite/files/8489079/Logs2.zip)

**Comment by theresalech** [comment]
This is blocked by https://github.com/smartdevicelink/sdl_hmi/issues/686.

**Comment by crokita** [comment]
Issue on the SDL HMI has been resolved.
