### ISSUE TITLE
Add Video Streaming to Protocol Layer

### ISSUE THREAD

**Issue by russjohnson09** [smartdevicelink/sdl_javascript_suite#54]
Add the ability to request an video service (referred to as a NAV service type but the javascript sdk refers to it as simply an video service type), send raw packets using this video service, and end the individual video service without closing the entire session.

**Comment by russjohnson09** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Add Video Streaming to Protocol Layer [1]](https://trello.com/c/KRTs5lAO/1351-2-add-video-streaming-to-protocol-layer-1)

**Comment by crokita** [comment]
Changed merged into develop
