### ISSUE TITLE
Console log printing wrong class name for _SoftButtonReplaceOperation

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#543]
### Bug Summary

The SoftButtonReplaceOperation class reports in the logs that it is the SoftButtonTransitionOperation class instead.

### Reproduction Steps

1. Cause a change in soft buttons that triggers the replace operation.

Expected Behavior:
Informative logs from SoftButtonReplaceOperation state it is the SoftButtonReplaceOperation class.

Observed Behavior:
SoftButtonReplaceOperation states it is the SoftButtonTransitionOperation class.

### JavaScript Version(s)

1.4.0

### sdl_javascript Version

1.4.0

### Testing Environment(s)

```markdown
Manticore 2.10.0
```

**Comment by theresalech** [comment]
Closed via #544
