### ISSUE TITLE
SdlArtwork clone issue

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#546]
### Bug Summary

[See original report from Java team](https://github.com/smartdevicelink/sdl_java_suite/issues/1818)

Cloning an SdlArtwork after having the artwork set its _imageRPC property (ex. through setPrimaryGraphic) gets the property passed to the clone as well. When trying to set the file name to something else and sending it again the _imageRPC is cached and will not change its value. The FileManager doesn't use _imageRPC but the text and graphic operation class does and this causes the wrong image to show up on the HMI.

### Reproduction Steps

1. Send an SdlArtwork via setPrimaryGraphic
2. Clone the SdlArtwork
3. Change its file name
4. Send it again via setPrimaryGraphic

Expected Behavior:
TextAndGraphicUpdateOperation uses the new file name in its _imageRPC and the right image is uploaded

Observed Behavior:
TextAndGraphicUpdateOperation uses the old file name in its _imageRPC and the wrong image is uploaded

### JavaScript Version(s)

1.5.0

### sdl_javascript Version

1.5.0

### Testing Environment(s)

```markdown
Manticore v2.10.0
```

**Comment by theresalech** [comment]
Closed via #549
