### ISSUE TITLE
DisplayCapabilities missing information in SystemCapabilityManager

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#551]
### Bug Summary

See related issues [here](https://github.com/smartdevicelink/sdl_java_suite/issues/1824) and [here](https://github.com/smartdevicelink/sdl_ios/issues/2105).

In the converted display capabilities, ScreenParams are null, MediaClockFormats are empty, and the DisplayCapability Window ID is null. 

### Reproduction Steps

1. Use the SCM's getDisplayCapabilities method and print its object. Also, check the stored displays Window ID in the SCM. 

Expected Behavior:
These properties exist or are not empty

Observed Behavior:
The properties do not exist or are empty.

### Which projects have you seen this bug on?

Vanilla JavaScript, Node.js

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Tested with Manticore 2.10.0
```

**Comment by theresalech** [comment]
Closed via #552
