### ISSUE TITLE
Missing SystemCapabilityManager Tests

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#553]
### Bug Summary

There are missing SCM tests in the JS Suite library. The JS Suite should align with the other libraries' tests for the SCM.

### Reproduction Steps

1. Run manager tests
 
Expected Behavior:
Tests should cover the SCM

Observed Behavior:
Tests do not cover the SCM

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Tested with Manticore v2.10.0
```

**Comment by theresalech** [comment]
Closed via #566
