### ISSUE TITLE
Setting bad data in one T&G field then good data quickly in another can lead to the good data failing.

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#554]
### Bug Summary

See the original issue that this issue is based on [here](https://github.com/smartdevicelink/sdl_ios/issues/1781). 

Failed updates to text and graphics in one field can cause a subsequent update in a different field to also fail, preventing a legitimate update from being displayed on the screen.

### Reproduction Steps

1. Set text field 1 to some string
2. Attempt to set text field 2 to an illegitimate string (ex. a string over 500 characters)
3. Attempt to set text field 2 to a legitimate string immediately after

Expected Behavior:
The illegitimate string fails and the legitimate string succeeds and is displayed.

Observed Behavior:
Both text field 2 strings fail and do not display.

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Manticore v2.10.0
```

**Comment by theresalech** [comment]
Closed via #555
