### ISSUE TITLE
Building the library fails on Node version 16.17 and higher major versions

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#556]
### Bug Summary

When doing a fresh install and build of dependencies on newer versions of NodeJS, the install fails due to resolving dependency issues with packages such as eslint.

### Reproduction Steps

1. Install Node version 16.17+ or 18.5+
2. Delete the node_modules directory if it exists
3. Run `npm install` and then `npm run build`

Expected Behavior:
The dependencies are installed and the node_modules folder created

Observed Behavior:
The installation fails mid-task

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Checked on NodeJS versions v16.17.0 and v18.9.0
```

**Comment by theresalech** [comment]
Closed via #557
