### ISSUE TITLE
Images not displaying correctly on Alerts sent via AlertManager

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#558]
### Bug Summary

This issue is related to the [Java Suite issue](https://github.com/smartdevicelink/sdl_java_suite/issues/1835)

When passing in a custom image to the icon property of an AlertView, the image is not displayed on the HMI.

### Reproduction Steps

1. Create an AlertView
2. Call setIcon and pass in an SdlArtwork with a custom image
3. Send it via screen manager's presentAlert

Expected Behavior:
The uploaded image displays in the alert on the Generic HMI

Observed Behavior:
A default image is displayed on the Generic HMI

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Manticore v2.10.0
```

**Comment by theresalech** [comment]
Closed via #561
